# Generated by Django 3.0.7 on 2020-07-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.IntegerField()),
                ('total_earnings', models.IntegerField()),
                ('rental_yield', models.IntegerField()),
            ],
        ),
    ]
