# Generated by Django 3.0.7 on 2020-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboad',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
