# Generated by Django 3.0.7 on 2020-07-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_dashboad_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('pan', models.CharField(blank=True, max_length=15)),
                ('pan_image', models.ImageField(blank=True, upload_to='images/')),
                ('adhaar', models.CharField(blank=True, max_length=100)),
                ('adhaar_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
