# Generated by Django 3.0.7 on 2020-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rentalyeild', models.IntegerField()),
                ('min_investment', models.IntegerField()),
                ('investors', models.IntegerField()),
            ],
        ),
    ]
